[package]
name = "ps-util"
version = "0.1.0"
authors = ["elbaro <elbaro@github>"]
edition = "2018"

[[bin]]
name = "psutil"
path = "src/main.rs"

[dependencies]
clap = "2.32.0"
rand = "0.5.5"
num-traits = "0.2.6"
piston2d-graphics = "0.26.0"
piston_window = "0.81.0"
indoc = "0.2.8"
chrono = "0.4.6"
walkdir = "2.2.5"
colored = "1.6.1"
select = "0.4.2"
reqwest = "0.9.2"
libc = "0.2.43"
regex = "1.0.5"
strum_macros = "0.11.0"
strum = "0.11.0"
wait-timeout = "0.1.5"
url = "1.7.1"
time = "0.1.40"
serde = "1.0.79"
cookie = "0.11.0"
fantoccini = "0.11.4"
tokio = { version = "0.1.11", features = ["async-await-preview"] }
tokio-async-await = "0.1.4"
serde_json = "1.0.32"
error-chain = "0.12.0"
# selenium-rs = "0.1.1"

[build-dependencies]
clap = "2.32.0"
indoc = "0.2.8"
